### ISSUE TITLE
Question about control statsd-tg metrics

### ISSUE THREAD

**Issue by keyboardfann** [octo/statsd-tg#3]
Dear All,
    statsd-tg is a good project for testing statsd,  Is there any way to control how many metrics and how many metric names in some time. With this feature I can verify the data integrity, how many data in and how many data out.
 
For Example:
1 min , 1M metrics , 4k metric name

Here is the script I test.
```
statsd-tg -d 10.62.4.240 -D 12000 -T 1 -s 0 -c 1000000 -t 0 -g 0
Sent 3674238 events in 5s (717730 events/s).
```

**Comment by octo** [comment]
Hi @keyboardfann, thanks for opening this issue. If I understand you correctly you need a way to control the number of metrics per second being sent? I suspect you want to load test rather than stress test?

Best regards,
—octo

**Comment by keyboardfann** [comment]
Dear @octo ,
    Thank you for the reply. Yes, so seems statsd-tg only support stress test and don't support load test feature now?

**Comment by keyboardfann** [comment]
Dear @octo,
    I use the dirty way to ensure around 100k/s event. 

```
while true;do statsd-tg -d 10.62.4.240 -D 12000 -T 1 -s 0 -c 1500000 -t 0 -g 0 & sleep 0.5s;pkill statsd-tg;sleep 3s;done

[1]+  Done                    statsd-tg -d 10.62.4.240 -D 12000 -T 1 -s 0 -c 1500000 -t 0 -g 0
[1] 11636
Sent 419582 events in 1s (825453 events/s).
```
